#macro CARDINAL_DIR round(oLouis.playerDirection/90)
#macro FRAME_RATE 60
#region Game Impacting
	global.firstDay = true;
	takingSoLong = false;
	takingSoLong2 = false;
	global.pathBlocker = undefined;
	global.underAttack = false;
	global.quickTheDoor = false;
	global.weLockedIn = false;
	global.justForShow = false;
	global.tape = false
	global.windowBroken = false;
	global.rations = false;
	global.rationsFound = false;
	global.iHaveKnife = false;
	global.brokenWindow = undefined;
	global.theChase = false;
	global.grid = undefined;
	global.theEnd = false;
	currentRations = 0;
#endregion
global.iCamera = instance_create_layer(0,0,layer,oCamera);
set = false;
set1 = false;
set2 = false;
set3 = false;
set4 = false;
set5 = false;
global.windowWidth = window_get_width();
global.windowHeight = window_get_height();
global.playerPaused = false;
inst = 0;
whatText = undefined;
theActualText = undefined;
global.oldLine = 0;
room = rIntro;
//text speeds
global.slow = .15;
global.medium = .25;
global.fast = .5;
global.knife = false;
global.gameOver = false;
global.waterGaugePercent =0;